import { useCallback } from "react";
import { useI18n } from "../../i18n/I18n";

// Display copy for the reorder list. English is the source; zh-CN is chosen by
// the interface language. Codes and values sent to the server are never
// translated.
const COPY = {
  "en-US": {
    title: "Reorder list",
    subtitle: "Items ranked by the day their stock position is expected to reach the recorded reorder point. Nothing is ordered automatically: open a prefilled purchase request, check it and submit it.",
    refresh: "Refresh",
    scopeAll: "All warehouses; transfers not considered",
    scopeReader: "Your {n} warehouses; transfers not considered",
    rule: "Stock position = on hand − reserved + incoming. Average daily demand = quantity shipped in the last {window} days ÷ {window}, with at least {min} shipment days. Order by = today + whole days until the position reaches the reorder point.",
    horizon: "Incoming purchase order lines due after an item's order-by date are not counted, and the date is worked out again. Without enough shipment history every incoming line is counted.",
    units: "Only purchase order and shipment lines in the item's stock unit are counted.",
    noReorderPoint: "{n} items have no reorder point and are not judged.",
    noReorderPointOne: "1 item has no reorder point and is not judged.",
    setIt: "Set it",
    supplierFilter: "Preferred supplier",
    allSuppliers: "All suppliers",
    noSupplier: "No preferred supplier",
    colOrderBy: "Order by",
    colItem: "Item",
    colOnHand: "On hand",
    colReserved: "Reserved",
    colIncoming: "Incoming",
    colPosition: "Position",
    colReorderPoint: "Reorder point",
    colDemand: "Daily demand",
    colShortfall: "Shortfall",
    colSupplier: "Preferred supplier",
    colAction: "Action",
    orderNow: "Order now",
    inDays: "in {n} days",
    inOneDay: "in 1 day",
    today: "today",
    demandDays: "{n} shipment days in {window}",
    notEnoughHistory: "Not enough shipment history ({n} days)",
    notRecorded: "Not recorded",
    leadTime: "Lead time {n} days",
    leadTimeNotRecorded: "Lead time not recorded",
    moq: "MOQ {n}",
    moqNotRecorded: "MOQ not recorded",
    createRequest: "Create purchase request",
    purchaseUnitDiffers: "Purchase unit differs ({unit}); enter the quantity",
    poOtherUnit: "{po} in {unit}, not counted",
    poOtherUnitHidden: "1 line in {unit}, not counted",
    poAfterOrderBy: "{po} due {day}, after the order-by date, not counted",
    poAfterOrderByHidden: "1 line due {day}, after the order-by date, not counted",
    poNoDueDay: "{po} has no due date; counted",
    poNoDueDayHidden: "1 line has no due date; counted",
    poUnitNotRecorded: "A purchase order line or the item has no unit recorded; counted",
    allIncomingCounted: "All incoming lines counted (no daily demand to date them against)",
    shipmentOtherUnit: "{count} shipment lines in {unit}, not counted",
    shipmentUnitNotRecorded: "{count} shipment lines without a unit; counted",
    stockUnitNotRecorded: "The item has no stock unit recorded",
    notJudgedTitle: "Not judged: stock incomplete",
    notJudgedBody: "These items have a reorder point, but their on hand, reserved or incoming quantity is not fully recorded.",
    emptyTitle: "No items to reorder",
    emptyBody: "Every item with a recorded reorder point is above it, or has too little shipment history to date it.",
    filteredEmpty: "No items for this supplier.",
    loading: "Loading the reorder list…",
    error: "Could not load the reorder list. Try again.",
    notAvailable: "The reorder list needs the workspace database.",
    reason: "Reorder list: stock position {position} against reorder point {reorderPoint}; order by {date}.",
    aboveWithoutHistory: "{n} items are above their reorder point with too little shipment history to date them; they are not listed.",
    aboveWithoutHistoryOne: "1 item is above its reorder point with too little shipment history to date it; it is not listed.",
    fromWarnings: "Open the reorder list: items ranked by the date to order, from their recorded reorder point and shipment history",
  },
  "zh-CN": {
    title: "补货清单",
    subtitle: "按库存头寸预计降到已记录再订货点的日期排列物料。系统不会自动下单：请打开预填的采购申请，核对后提交。",
    refresh: "刷新",
    scopeAll: "全部仓库；未考虑调拨",
    scopeReader: "你的 {n} 个仓库；未考虑调拨",
    rule: "库存头寸 = 在手 − 预留 + 在途。日均需求 = 最近 {window} 天的发货数量 ÷ {window}，且至少有 {min} 个发货日。最晚下单日 = 今天 + 头寸降到再订货点前的整天数。",
    horizon: "到货日期晚于最晚下单日的采购订单行不计入，并重新计算日期。发货历史不足时计入全部在途行。",
    units: "只计入与物料库存单位相同的采购订单行和发货行。",
    noReorderPoint: "{n} 个物料没有再订货点，未作判断。",
    noReorderPointOne: "1 个物料没有再订货点，未作判断。",
    setIt: "去设置",
    supplierFilter: "首选供应商",
    allSuppliers: "全部供应商",
    noSupplier: "无首选供应商",
    colOrderBy: "最晚下单日",
    colItem: "物料",
    colOnHand: "在手",
    colReserved: "预留",
    colIncoming: "在途",
    colPosition: "头寸",
    colReorderPoint: "再订货点",
    colDemand: "日均需求",
    colShortfall: "缺口",
    colSupplier: "首选供应商",
    colAction: "操作",
    orderNow: "立即下单",
    inDays: "{n} 天后",
    inOneDay: "1 天后",
    today: "今天",
    demandDays: "{window} 天内 {n} 个发货日",
    notEnoughHistory: "发货历史不足（{n} 天）",
    notRecorded: "未记录",
    leadTime: "提前期 {n} 天",
    leadTimeNotRecorded: "提前期未记录",
    moq: "最小起订量 {n}",
    moqNotRecorded: "最小起订量未记录",
    createRequest: "创建采购申请",
    purchaseUnitDiffers: "采购单位不同（{unit}）；请填写数量",
    poOtherUnit: "{po} 以 {unit} 计，未计入",
    poOtherUnitHidden: "1 行以 {unit} 计，未计入",
    poAfterOrderBy: "{po} 于 {day} 到货，晚于最晚下单日，未计入",
    poAfterOrderByHidden: "1 行于 {day} 到货，晚于最晚下单日，未计入",
    poNoDueDay: "{po} 没有到货日期；已计入",
    poNoDueDayHidden: "1 行没有到货日期；已计入",
    poUnitNotRecorded: "有采购订单行或物料未记录单位；已计入",
    allIncomingCounted: "已计入全部在途行（没有日均需求可用来按日期筛选）",
    shipmentOtherUnit: "{count} 个发货行以 {unit} 计，未计入",
    shipmentUnitNotRecorded: "{count} 个发货行没有单位；已计入",
    stockUnitNotRecorded: "物料未记录库存单位",
    notJudgedTitle: "未判断：库存数据不完整",
    notJudgedBody: "这些物料有再订货点，但在手、预留或在途数量没有完整记录。",
    emptyTitle: "没有需要补货的物料",
    emptyBody: "所有已记录再订货点的物料都高于再订货点，或发货历史不足以推算日期。",
    filteredEmpty: "该供应商下没有物料。",
    loading: "正在读取补货清单…",
    error: "补货清单读取失败，请重试。",
    notAvailable: "补货清单需要工作区数据库。",
    reason: "补货清单：库存头寸 {position}，再订货点 {reorderPoint}；最晚下单日 {date}。",
    aboveWithoutHistory: "{n} 个物料高于再订货点但发货历史不足，无法推算日期，未列出。",
    aboveWithoutHistoryOne: "1 个物料高于再订货点但发货历史不足，无法推算日期，未列出。",
    fromWarnings: "打开补货清单：按已记录的再订货点和发货历史，按最晚下单日排列物料",
  },
} as const;

export type ReorderListCopyKey = keyof (typeof COPY)["en-US"];

export function reorderListText(language: string, key: ReorderListCopyKey, params: Record<string, string | number> = {}) {
  const table = COPY[language === "zh-CN" ? "zh-CN" : "en-US"];
  return Object.entries(params).reduce((value, [name, replacement]) => value.split(`{${name}}`).join(String(replacement)), table[key] as string);
}

export function useReorderListCopy() {
  const { language } = useI18n();
  return useCallback((key: ReorderListCopyKey, params?: Record<string, string | number>) => reorderListText(language, key, params), [language]);
}
