const zh: Record<string, string> = {
  'New supplier': '新增供应商', 'Edit supplier': '编辑供应商', 'Save supplier': '保存供应商', 'Saving…': '正在保存…', 'Cancel': '取消',
  'Start with the essentials. Add contact and commercial details when available.': '先填写必要资料，再补充联系方式和商务信息。',
  'Basic information': '基本信息', 'Contact and address': '联系与地址', 'Commercial terms': '商业条款', 'Tax and bank details': '财税与银行',
  'Optional': '选填', 'Required fields': '必填字段', 'Supplier code': '供应商编号', 'Supplier name': '供应商名称', 'Short name': '简称',
  'Business type': '经营类型', 'Categories': '经营品类', 'Contact name': '联系人', 'Phone': '联系电话', 'Email': '邮箱', 'Address': '地址',
  'Postal / ZIP code': '邮编', 'Delivery lead time (days)': '送货周期（天）', 'Default currency': '默认币种', 'Payment terms': '付款条款',
  'Settlement method': '结算方式', 'Business registration ID': '企业登记号', 'Tax ID': '税号', 'Bank name': '银行', 'Account holder': '户名',
  'Account number': '银行账号', 'Internal notes': '内部备注', 'Status': '状态', 'Active': '启用', 'Inactive': '停用', 'Draft': '草稿',
  'Use a unique code, such as SUP-001.': '使用唯一编号，例如 SUP-001。', 'Separate categories with commas.': '多个品类请用逗号分隔。',
  'Tax identifiers depend on the supplier’s country.': '税务登记信息取决于供应商所在国家。', 'Supplier saved': '供应商已保存',
  'Enter a supplier code.': '请填写供应商编号。', 'Enter a supplier name.': '请填写供应商名称。', 'Enter a valid email address.': '请填写有效邮箱。',
  'Lead time must be a whole number of days, zero or greater.': '送货周期必须为零或正整数天。', 'Choose a valid currency.': '请选择有效币种。',
  'Check the highlighted fields.': '请检查标记的字段。', 'This supplier code is already in use.': '该供应商编号已被使用。',
  'This supplier changed. Reopen it and try again.': '供应商已被修改，请重新打开后再试。', 'Could not save supplier. Please try again.': '供应商保存失败，请重试。',
  'Could not load workspace currency. Choose a currency before saving.': '无法读取工作区币种，请在保存前选择币种。', 'Choose currency': '选择币种',
  'Not recorded': '未记录', 'Choose one of the workspace payment terms.': '请选择工作区中的付款条款。',
  'Could not load the workspace payment terms. The stored term is kept.': '无法读取工作区付款条款，已保留现有条款。',
  'Leave empty when the term is not agreed yet.': '尚未约定付款条款时请留空。',
  'Back to suppliers': '返回供应商列表', 'Edit': '编辑', 'Supplied items': '可供应物料', 'Select SKU': '选择 SKU', 'Reference price': '参考价格',
  'Add supplied item': '新增供应商关系', 'No supplied items yet': '暂无可供应物料', 'Set as preferred': '设为首选', 'Yes': '是', 'No': '否',
  'Purchase records': '采购记录', 'No purchase records available': '暂无采购交易记录', 'Risks and exceptions': '风险与异常', 'No risks or exceptions available': '暂无风险或异常',
  'Supplied-item links are currently unavailable.': '可供应物料关联暂不可用。',
  'Preferred': '首选', 'Approved': '已批准', 'Lead Time': '交期', 'MOQ': '最小起订量',
  // Supplier tiers and business owners.
  'Tier 1 Strategic': '一级 · 战略', 'Tier 2 Core': '二级 · 核心', 'Tier 3 Transactional': '三级 · 一般', 'Not tiered': '未分级',
  'Tier 1': '一级', 'Tier 2': '二级', 'Tier 3': '三级', 'Tier': '层级', 'All': '全部', 'Managed by me': '我负责的', 'Supplier list': '供应商列表',
  'Losing this supplier would stop sales or operations soon. Needs a named owner and regular review.': '失去该供应商会很快影响销售或运营，需要指定负责人并定期复核。',
  'A regular, approved source, with alternatives or limited impact.': '常用的已批准来源，有替代来源或影响有限。',
  'Occasional or low-impact purchases.': '偶尔采购或影响较小的采购。', 'Nobody has decided yet.': '尚未确定层级。',
  'Change tier': '调整层级', 'Reason': '原因', 'Set by': '设置人', 'Workspace setup': '工作区初始化', 'Save tier': '保存层级', 'Tier saved': '层级已保存',
  'Business owner': '业务负责人', 'Change owner': '更换负责人', 'No owner': '无负责人', 'Save owner': '保存负责人', 'Owner saved': '负责人已保存',
  'All owners': '全部负责人', 'Owner filter': '负责人筛选', 'The person who manages this supplier relationship.': '负责维护该供应商关系的人。',
  'Why this tier? For example: the only approved source of our best-selling item.': '为什么定这个层级？例如：它是我们畅销物料唯一的已批准来源。',
  'Tier and owner history': '层级与负责人记录', 'Suggestion accepted': '采纳了系统建议', 'Could not load workspace users.': '无法读取工作区用户。',
  'Could not save. Please try again.': '保存失败，请重试。', 'Enter a reason of 3 to 500 characters.': '请填写 3 到 500 个字的原因。',
  'Choose Tier 1, 2 or 3, or Not tiered.': '请选择一级、二级、三级或未分级。', 'Choose a different tier.': '请选择不同的层级。',
  'Choose an active user of this workspace.': '请选择本工作区的在职用户。', 'Choose a different owner.': '请选择不同的负责人。',
  // Supplier metrics.
  'Supplier': '供应商',
  'Spend, 12 months': '近 12 个月花费', 'Open POs': '未完成 PO', 'Overdue POs': '逾期 PO', 'On time (PO date), 90 days': '90 天准时率（按采购订单日期）', 'Open issues': '未结问题',
  'Hidden for your role': '你的角色不可见', 'Fewer than 5 deliveries in 90 days': '90 天内交付不足 5 次，暂不计算',
  "{count} of {of} deliveries on time against the date on the PO, which may be the buyer's need date": '{of} 次交付中 {count} 次按采购订单日期准时（该日期可能是采购方的需求日期）',
  'Set inactive': '设为停用', 'Set active': '设为启用', 'Supplier search': '供应商查询', 'Search suppliers by code, name, status, category and owner.': '按编号、名称、状态、品类和负责人查询供应商。', 'Search': '搜索',
  'Sort by': '排序', 'Name': '名称', 'Spend': '花费', 'Overdue': '逾期', 'Issues': '问题', 'currencies': '种币种',
  // Supplier evaluation: indicators per supplier, with the tier a person sets.
  'All tiers': '全部层级', 'Tier filter': '层级筛选', 'All statuses': '全部状态', 'Status filter': '状态筛选', 'Reset': '重置', 'Refresh': '刷新',
  'Search suppliers': '搜索供应商', 'Code or name': '编号或名称', 'Actions': '操作', 'Set tier': '设置层级',
  'Filter suppliers by name, tier, owner and status, and compare their indicators.': '按名称、层级、负责人和状态筛选供应商，并比较各项指标。',
  'Supplier indicators': '供应商指标', '{total} suppliers, {shown} shown': '共 {total} 家供应商，当前显示 {shown} 家', '1 supplier, {shown} shown': '共 1 家供应商，当前显示 {shown} 家',
  "Tiers are set by your team with a reason and kept in each supplier's history. FlowChain does not suggest tiers.": '层级由团队填写原因后设置，并记入每家供应商的历史。系统不会建议层级。',
  'Spend, highest first': '花费从高到低', 'Open POs, most first': '未完成 PO 从多到少', 'Overdue POs, most first': '逾期 PO 从多到少',
  'On time, lowest first': '准时率从低到高', 'Open issues, most first': '未结问题从多到少',
  'No suppliers match these filters': '没有符合筛选条件的供应商', 'Reset the filters to see every supplier.': '重置筛选即可查看全部供应商。',
  'No suppliers yet': '暂无供应商', 'Add suppliers on the Suppliers tab, or import a file of suppliers, to evaluate them here.': '在“供应商”页新增或导入供应商后，即可在此评估。',
  'Could not load suppliers.': '供应商数据加载失败。', 'Retry': '重试', 'Loading…': '正在加载…',
  'Indicators could not be loaded. Refresh to try again.': '指标加载失败，请刷新重试。',
  // Supplier risks: every supplier's open issues, the earliest date first.
  'Overdue purchase orders': '逾期采购订单', 'Receipts with rejections': '有拒收的收货', 'Received, not posted': '已收货未过账', 'Invoice variances': '发票差异',
  'Past their promised date': '已过承诺交期', 'A quantity was rejected on receipt': '收货时有数量被拒收', 'Not yet posted to inventory': '尚未过账入库',
  'Invoices that differ from the PO or receipt': '与采购订单或收货不一致的发票',
  'Supplier risk search': '供应商风险查询', 'Search open issues by supplier and issue type.': '按供应商和问题类型查询未结问题。',
  'Supplier code or name': '供应商编号或名称', 'Issue type': '问题类型', 'All issue types': '全部问题类型', 'Issue type filter': '问题类型筛选',
  '{total} issues, {shown} shown': '共 {total} 个问题，当前显示 {shown} 个', '1 issue, {shown} shown': '共 1 个问题，当前显示 {shown} 个',
  'Date': '日期', 'Issue': '问题说明', 'Document': '单据', 'Days overdue': '逾期天数', 'Promised date': '承诺交期', 'Open since': '发生日期',
  'Earliest date first: an overdue purchase order by its promised date, any other issue by the day it started. Never ordered by a score.': '按日期从早到晚排列：逾期采购订单按承诺交期，其他问题按发生日期，从不按评分排序。',
  'No open supplier issues': '暂无未结的供应商问题',
  'Overdue purchase orders, rejected or unposted receipts and invoice variances are listed here when they happen. Nothing needs following up now.': '逾期采购订单、拒收或未过账的收货以及发票差异出现时会列在这里。目前无需跟进。',
  'No issues match these filters': '没有符合筛选条件的问题', 'Reset the filters to see every open issue.': '重置筛选即可查看全部未结问题。',
  'Hidden for your role: you cannot read the purchase orders, receipts or supplier invoices behind these issues.': '你的角色不可见：你无法查看这些问题对应的采购订单、收货或供应商发票。',
  'Some kinds of issue are hidden for your role: {kinds}.': '部分问题类型对你的角色不可见：{kinds}。',
  'Could not load supplier risks.': '供应商风险加载失败。',
};
const en = Object.fromEntries(Object.entries(zh).map(([key, value]) => [value, key]));
// The English to Chinese pairs, read by the owner-rule tests.
export const supplierCopyPairs: Readonly<Record<string, string>> = zh;
export const supplierCopy = (value: string, language: string) => language === 'en-US' ? en[value] || value : zh[value] || value;
