// Presentation labels only. Do not translate record names or identifiers.
const chinese: Record<string, string> = {
  'Mixed units': '混合计量单位',
  'Restricted': '受限', 'Your role cannot view this figure': '你的角色无权查看此数据', 'Your role cannot view amounts.': '你的角色无权查看金额。',
  'Inventory uses different units; quantities are shown by SKU without a combined stock total.': '库存使用不同计量单位，数量按 SKU 展示，不合计在手总量。',
  'Undated': '无日期', 'Unspecified': '未指定', 'Status': '状态', 'Quantity': '数量', 'Amount': '金额', 'Available': '可用量', 'Shortage': '缺口',
  'Supplier count': '供应商数量', 'Supplier invoice amount': '供应商发票金额', 'Open POs': '开放 PO',
  'On-hand inventory': '在手库存', 'Unfulfilled sales demand': '未履约销售需求',
  'Count of sales orders in the current range.': '当前范围内真实销售订单记录数。',
  'Ordered quantity less fulfilled quantity, before inventory reservations.': '订单数量扣除已履约数量，不扣减库存预留。',
  'Ordered less fulfilled quantity on confirmed sales order lines, before inventory reservations. Shown only while every line with demand left is the same SKU in the same unit.': '已确认销售订单行的订购数量扣除已履约数量，不扣减库存预留；仅当所有未履约行为同一 SKU、同一单位时显示合计。',
  'Multiple SKUs': '多个 SKU', 'See open demand by SKU': '请按 SKU 查看未履约需求', 'See on hand by SKU': '请按 SKU 查看在手库存',
  "Ordered less shipped quantity, in each SKU's unit. Bars in different units are not comparable.": '订购数量减去已发货数量，按各 SKU 自身单位计。不同单位的柱形不可比较。',
  'Share of confirmed sales orders whose every line has shipped its ordered quantity.': '每一行均已按订购数量全部发货的已确认销售订单占比。',
  'Total of committed purchase orders (approved, issued, partially received or fully received). Drafts and orders pending approval, rejected or cancelled are excluded. No total is shown while a committed order has no amount.': '已承诺采购订单（已批准、已下达、部分收货或全部收货）的金额合计，不含草稿、待审批、驳回和取消的订单；有订单缺少金额时不显示合计。',
  'Purchase orders that are committed (approved, issued, or partially received) and still have quantity to receive.': '已承诺（已批准、已下达或部分收货）且仍有待收数量的采购订单数。',
  'On-hand quantity recorded in inventory. Shown only while all inventory is the same SKU in the same unit.': '库存中已记录的在手数量；仅当全部库存为同一 SKU、同一单位时显示合计。',
  'SKUs with a shortage under the shared availability calculation.': '按统一 availability 口径存在 shortage 的 SKU 数。',
  'Total of submitted supplier invoices (submitted, matching, exception, matched, approved or held). Drafts and rejected or cancelled invoices are excluded. No total is shown while an invoice has no amount.': '已提交供应商发票（已提交、匹配中、有差异、已匹配、已批准或暂挂）的金额合计，不含草稿、驳回和取消的发票；有发票缺少金额时不显示合计。',
  'Some committed documents have no amount, so their total is not shown.': '部分已承诺单据缺少金额，因此不显示合计。',
  'Amount missing on some records': '部分记录缺少金额',
  'Missing or invalid currency': '币种缺失或无效',
  'Some records have a missing or invalid currency code, so their amounts are not totaled.': '部分记录的币种缺失或无效，因此不合计这些金额。',
  'Count of supplier master records.': '当前供应商主数据记录数。',
  'No business records in this range': '当前范围无真实业务记录',
  'No records in the selected range.': '当前筛选范围暂无业务记录。',
  'Change chart visibility and order. Your layout is saved in the page link.': '调整图表显示与顺序；结果会保留在当前 URL。',
  'Close customization': '关闭调整当前视图', 'Ranking size': '排行榜显示数量', 'Chart visibility and order': '图表显示与顺序',
  'Hidden': '已隐藏', 'Visible': '已显示', 'Move up': '上移', 'Move down': '下移', 'Restore default layout': '恢复默认布局',
  'Current filtered scope': '当前筛选范围', 'Calculation': '口径说明', 'Date field': '时间字段', 'Version': '版本',
  'Dashboard filtered': '已筛选当前看板', 'Kept after refresh': '刷新页面后仍会保留', 'Keep at least one chart visible': '至少保留一个可见图表',
  'Name this view': '保存当前视图名称', 'View saved': '视图已保存', 'Could not save view': '保存视图失败', 'Please try again': '请重试',
  'Workbook exported': '看板工作簿已导出', 'Could not export workbook': '导出失败',
  'Single currency': '单一币种', 'Filtered currency': '已筛选币种', 'Currency code': '币种代码', 'Currency name': '币种显示名称',
  'Currency aggregation': '币种汇总状态', 'FX converted': '是否已汇率折算', 'Yes': '是', 'No': '否',
  'Chart': '图表名称', 'Dimension': '维度', 'Series': '系列', 'Value': '数值', 'Uncategorized': '未分类',
  'Metric summary': '指标摘要', 'Metric': '指标名称', 'Current value': '当前值', 'Baseline value': '上期值', 'Change': '变化',
  'Definition': '中文定义', 'Data range': '数据范围', 'Chart data': '图表数据', 'Detail data': '明细数据', 'Filters': '筛选条件',
  'Not compared': '未比较', 'Numerator': '分子', 'Denominator': '分母', 'Not applicable': '不适用', 'Metric version': '指标版本',
  'Data limitations': '数据限制', 'None': '无', 'Source subject': '来源对象', 'Reserved': 'reserved', 'Fulfilled': 'fulfilled',
  'Operational snapshot': '运营概览', 'See what changed. Focus on what needs attention.': '查看业务变化，优先关注待处理事项。',
  'Record activity by month': '每月业务记录活动', 'Purchase orders': '采购订单', 'Sales orders': '销售订单',
  'Purchase order status': '采购订单状态', 'Purchasing by supplier': '按供应商统计采购订单',
  'Needs attention': '需要关注', 'Open purchase orders': '未完成采购订单', 'Inventory shortages': '库存短缺',
  'Unfulfilled sales orders': '未履约销售订单', 'Review orders': '查看订单', 'Review inventory': '查看库存',
  'Counts use the current filters. Select a card to review the source records.': '数量基于当前筛选，点击卡片查看来源记录。',
  "Activity uses each order's order date, falling back to its creation date. Counts are orders, not revenue.": '活动按订单日期统计，缺失时使用创建日期。数量表示订单数，并非收入。',
  'Purchase order details': '采购订单明细', 'Sales order details': '销售订单明细', 'Inventory details': '库存明细', 'Invoice details': '发票明细', 'Supplier details': '供应商明细',
  'Showing': '显示', 'of': '共', 'records in the loaded scope': '条已加载范围内的记录',
  'Dates must use YYYY-MM-DD.': '日期必须使用 YYYY-MM-DD。', 'Start date must not be after end date.': '开始日期不得晚于结束日期。',
  'Record date': '记录日期', 'Current workspace records': '当前工作区数据', 'Business records': '业务记录',
  'Stock status': '库存状态',
  // Dashboard visuals.
  'Committed spend by month': '每月已承诺采购额', 'Purchase order lifecycle': '采购订单生命周期', 'Spend concentration by supplier': '供应商采购集中度',
  'Ordered, received and invoiced value': '订购、收货与开票金额', 'Committed spend by supplier and item': '按供应商和物料的已承诺采购额', 'Purchase orders by supplier': '按供应商统计采购订单数',
  'Receiving activity by day': '每日收货活动', 'Submitted invoices by month': '每月已提交发票', 'Invoices matched': '发票匹配通过率', 'Match outcome': '匹配结果',
  'Invoices from supplier to match outcome': '从供应商到匹配结果的发票流向', 'Invoice variance by supplier': '按供应商统计发票差异', 'Invoice status': '发票状态',
  'Sales orders by month': '每月销售订单', 'Sales order fulfillment': '销售订单履约', 'Sales concentration by customer': '客户销售集中度', 'Orders shipped in full': '全部发货订单占比',
  'Open demand by SKU': '按 SKU 统计未履约需求', 'Sales order status': '销售订单状态', 'On hand by SKU': '按 SKU 统计在手库存', 'Stock position by SKU': '按 SKU 统计库存状况',
  'Available to promise by SKU': '按 SKU 统计可承诺量', 'SKUs by stock status and risk': '按库存状态和风险统计 SKU', 'Supplier performance matrix': '供应商绩效矩阵',
  'Supplier scorecard': '供应商记分卡', 'On-time receipts by supplier': '按供应商统计准时收货率', 'Purchase orders by supplier and month': '按供应商和月份统计采购订单',
  'Committed purchase orders by order date. Bars are amounts, the line is the number of orders.': '已承诺采购订单，按订单日期统计。柱形为金额，折线为订单数。',
  'Sorted by amount. The line is the running share of the total; A, B and C classes split at 80% and 95%.': '按金额排序。折线为累计占比；A、B、C 类以 80% 和 95% 划分。',
  'Amounts need one currency, so documents are counted. The line is the running share of the total.': '金额需要单一币种，因此按单据数量统计。折线为累计占比。',
  'Committed purchase orders in range. Each stage counts the orders that reached it and every stage before it.': '当前范围内的已承诺采购订单。每个阶段统计已到达该阶段及之前所有阶段的订单。',
  'Committed purchase orders in range, net of tax: ordered and received quantities at the order price, and the invoice lines linked to each order.': '当前范围内的已承诺采购订单（不含税）：订购和收货数量按订单单价计算，开票为关联到各订单的发票行。',
  'Select a currency to compare amounts.': '请选择币种以比较金额。',
  'Some order lines have no quantity or price, so the value bridge is not shown.': '部分订单行缺少数量或单价，因此不显示金额桥。',
  'Amounts need one currency, so purchase orders are counted per supplier.': '金额需要单一币种，因此按供应商统计采购订单数。',
  'Sized by committed order amount. Select a supplier to see the net line value of each item ordered.': '按已承诺订单金额显示大小。点击供应商可查看各物料的不含税行金额。',
  'Receipts per arrival day.': '按到货日期统计的收货单数量。',
  'Bubble size is the number of receipts. The guides are the median spend and the average on-time rate.': '气泡大小表示收货单数量。参考线为采购额中位数和平均准时率。',
  'No receipts with an expected date in the selected range.': '当前范围内没有带预计日期的收货记录。',
  'The largest suppliers by spend, on measures each of them has data for.': '采购额最大的供应商，仅比较每家都有数据的指标。',
  'Not enough receipt and invoice history to compare suppliers.': '收货和发票记录不足，无法比较供应商。',
  'Committed purchase orders, by order date.': '已承诺采购订单，按订单日期统计。',
  'Share of submitted invoices whose three-way match passed.': '已提交发票中三单匹配通过的比例。',
  'Submitted invoices by three-way match result.': '已提交发票按三单匹配结果统计。',
  'Each band is a number of submitted invoices.': '每条流带表示已提交发票的数量。',
  'Absolute variance between invoices and their orders and receipts.': '发票与订单、收货之间差异金额的绝对值。',
  'No invoice variance in the selected range.': '当前范围内没有发票差异。',
  'Submitted supplier invoices by invoice date. Bars are amounts, the line is the number of invoices.': '已提交供应商发票，按发票日期统计。柱形为金额，折线为发票数。',
  'Confirmed sales orders by order date. Bars are amounts, the line is the number of orders.': '已确认销售订单，按订单日期统计。柱形为金额，折线为订单数。',
  'Confirmed sales orders in range, without drafts and cancellations. Each stage counts the orders that reached it.': '当前范围内的已确认销售订单，不含草稿和已取消订单。每个阶段统计已到达该阶段的订单。',
  'Share of confirmed sales orders whose ordered quantity has shipped.': '订购数量已全部发货的已确认销售订单占比。',
  "Ordered less shipped quantity, in each SKU's unit.": '订购数量减去已发货数量，按各 SKU 自身单位计。',
  "Recorded on-hand quantity, in each SKU's unit.": '已记录的在手数量，按各 SKU 自身单位计。',
  'Each SKU in its own unit. Shortage is demand that available stock and incoming receipts do not cover.': '每个 SKU 使用自身单位。缺口为可用库存和在途收货无法覆盖的需求。',
  "On hand plus incoming, less reservations and open demand, in each SKU's unit. Negative values cannot be promised.": '在手加在途，减去预留和未履约需求，按各 SKU 自身单位计。负值表示无法承诺。',
  'Number of SKUs in each combination.': '每种组合下的 SKU 数量。',
  "Receipts that arrived on or before the purchase order's expected date.": '在采购订单预计日期当天或之前到货的收货单。',
  'Committed amount': '已承诺金额', 'Cumulative share': '累计占比', 'Invoice amount': '发票金额', 'Invoices': '发票数', 'Order amount': '订单金额',
  'Reserved quantity': '已预留数量', 'On-time receipts': '准时收货率', 'Receipts': '收货单数', 'Lines accepted in full': '全数验收的收货行',
  'Share of spend': '采购额占比', 'Share of orders': '订单数占比',
  'Committed': '已承诺', 'Receiving started': '已开始收货', 'Fully received': '已全部收货', 'Invoiced': '已开票', 'Invoice matched': '发票已匹配',
  'Active orders': '有效订单', 'Reserved or shipped': '已预留或已发货', 'Shipped': '已发货', 'Shipped in full': '已全部发货',
  'Ordered': '订购', 'Not yet received': '尚未收货', 'Received above order': '超订单收货', 'Received': '已收货', 'Received, not invoiced': '已收货未开票', 'Invoiced above receipts': '开票超过收货',
  'Total': '合计', 'Decrease': '减少', 'Increase': '增加', 'Matched': '已匹配', 'Match exception': '匹配异常', 'Awaiting match': '待匹配',
  'Other suppliers': '其他供应商', 'Other customers': '其他客户', 'All suppliers': '全部供应商', 'Median': '中位数', 'Average': '平均值', 'More': '多', 'Less': '少',
  'Class A': 'A 类', 'Class B': 'B 类', 'Class C': 'C 类', 'Share of first stage': '占首阶段比例', 'From previous stage': '较上一阶段',
  'Count': '数量', 'Share': '占比', 'Date': '日期', 'Stage': '阶段', 'Flow': '流向', 'Category': '类别',
  'Amounts are in more than one currency, so documents are counted. Select a currency to compare amounts.': '金额涉及多个币种，因此按单据数量统计。请选择币种以比较金额。',
  'Some records have no valid currency, so documents are counted. Select a currency to compare amounts.': '部分记录缺少有效币种，因此按单据数量统计。请选择币种以比较金额。',
  'Some documents have no amount and are left out of the amounts.': '部分单据缺少金额，未计入金额。',
  // Dashboard KPIs.
  'Overdue open POs': '逾期未完成 PO', 'Open purchase orders whose expected date is before today in the workspace timezone.': '预计日期早于工作区时区今天的未完成采购订单。',
  "Share of receipts in range that arrived on or before the purchase order's expected date. Receipts without an expected date are left out.": '当前范围内在采购订单预计日期当天或之前到货的收货单占比，不含没有预计日期的收货单。',
  'Suppliers with committed orders': '有已承诺订单的供应商', 'Suppliers with at least one committed purchase order in range.': '当前范围内至少有一张已承诺采购订单的供应商。',
  'Share of submitted supplier invoices whose three-way match passed.': '已提交供应商发票中三单匹配通过的比例。',
  'Invoices awaiting match': '待匹配发票', 'Submitted supplier invoices without a three-way match result yet.': '尚无三单匹配结果的已提交供应商发票。',
  'Match exceptions': '匹配异常发票', 'Submitted supplier invoices whose three-way match found an exception.': '三单匹配发现异常的已提交供应商发票。',
  'Sales order amount': '销售订单金额', 'Total of sales orders in the current range, without drafts and cancellations. No total is shown across currencies.': '当前范围内销售订单的金额合计，不含草稿和已取消订单；多币种时不显示合计。',
  'Out-of-stock SKUs': '缺货 SKU', 'SKUs with no available stock under the shared availability calculation.': '按统一可用量口径没有可用库存的 SKU。',
  'SKUs short against demand': '需求缺口 SKU', 'SKUs whose available-to-promise quantity is below zero.': '可承诺量低于零的 SKU。',
  // One definition per figure: shortage before and after incoming orders,
  // overdue by the earliest open line, on time against the original promise.
  'Committed PO amount': '已承诺采购订单金额',
  'SKUs short now': '当前缺货 SKU', 'SKUs whose open sales demand, less its reservations, is more than the available stock. Incoming purchase orders are not counted.': '未履约销售需求（扣除其预留）超过可用库存的 SKU，不计入在途采购订单。',
  'SKUs short after incoming': '计入在途后仍短缺 SKU', 'SKUs whose available-to-promise quantity (available stock plus incoming purchase orders, less open demand) is below zero.': '可承诺量（可用库存加在途采购订单，减去未履约需求）低于零的 SKU。',
  'Short now': '当前缺口', 'Available to promise': '可承诺量',
  'Each SKU in its own unit. Shortage is open demand that available stock does not cover; incoming purchase orders are not counted.': '每个 SKU 使用自身单位。缺口为可用库存无法覆盖的未履约需求，不计入在途采购订单。',
  "Open purchase orders whose earliest line still to receive was due before today in the workspace timezone (the line's promised date, else the order's expected date).": '最早一条未收货行的到期日早于工作区时区今天的未完成采购订单（取该行承诺日期，缺失时取订单预计日期）。',
  'On-time deliveries (date on the PO)': '按采购订单日期准时交付', "Deliveries (the lines of one PO with one date) first promised in range whose every line had a posted receipt by the date on the PO, which may be the buyer's need date. Orders approved but not sent to the supplier are left out. Needs at least 5 deliveries.": '原承诺日期在当前范围内的交付（同一采购订单、同一承诺日期的各行）中，每一行首次过账收货都在采购订单日期当天或之前到达的占比；该日期可能是采购方的需求日期。已审批但未发给供应商的采购订单不计入。至少需要 5 次交付。',
  'Fewer than 5 deliveries': '交付少于 5 次', 'Needs at least 5 deliveries': '至少需要 5 次交付',
  'Not measured': '未计量', 'Not every receipt could be loaded': '未能读取全部收货记录', 'Your role cannot view receipts.': '你的角色无权查看收货记录。',
  'Not every receipt could be loaded, so on-time deliveries are not measured here.': '未能读取全部收货记录，因此此处不计量准时交付。',
  'Range longer than the scorecard allows': '范围超过供应商评分卡允许的天数',
  'The range is longer than the supplier scorecard allows, so on-time deliveries are not measured. Choose a shorter range.': '日期范围超过供应商评分卡允许的天数，因此不计量准时交付。请选择更短的范围。',
  'Last 90 days': '最近 90 天',
  'On-time deliveries': '准时交付占比', 'Deliveries': '交付次数', 'On-time deliveries by supplier': '按供应商统计准时交付占比',
  'Deliveries (the lines of one PO with one date) first promised in range whose every line had a posted receipt by the date on the PO. Orders approved but not sent to the supplier are left out. Each supplier needs at least 5 deliveries.': '原承诺日期在当前范围内的交付（同一采购订单、同一承诺日期的各行）中，每一行首次过账收货都在采购订单日期当天或之前到达的占比。已审批但未发给供应商的采购订单不计入。每家供应商至少需要 5 次交付。',
  'No supplier has 5 or more deliveries first promised in the selected range.': '当前范围内没有供应商拥有 5 次或以上按原承诺计量的交付。',
  'Deliveries on time against the date on the PO. Bubble size is the number of deliveries measured. The guides are the median spend and the average on-time rate.': '按采购订单日期计算交付准时率。气泡大小表示计量的交付次数。参考线为采购额中位数和平均准时率。',
  'Committed purchase orders by supplier': '按供应商统计已承诺采购订单', 'Committed purchase orders in range (approved, issued or received), counted per supplier.': '当前范围内已承诺（已批准、已下达或已收货）的采购订单，按供应商计数。',
  'All purchase orders in range, every status.': '当前范围内全部状态的采购订单。',
  'Purchase and sales orders in range by order date, every status, drafts included.': '当前范围内的采购订单和销售订单，按订单日期统计，包含草稿在内的全部状态。',
  // Visual cards, insights and date ranges.
  'Focus mode': '聚焦模式', 'Close focus mode': '退出聚焦模式', 'Show data': '查看数据', 'Show chart': '查看图表', 'Download image': '下载图片', 'Download CSV': '下载 CSV',
  'Select a row to filter the dashboard.': '点击行可筛选当前看板。', 'Chart image downloaded': '图表图片已下载', 'Chart data downloaded': '图表数据已下载', 'Could not download the chart': '图表下载失败',
  'Select the chart to filter this dashboard': '点击图形可筛选当前看板', 'View business details': '查看业务明细',
  'Key insights': '关键洞察', 'Generated from the figures on this page.': '根据本页数据自动生成。', 'Monthly trend': '月度趋势',
  'From': '自', 'Through': '截至', 'Risk': '风险', 'Could not load': '加载失败',
  'Warehouse locations are not shown in this report.': '本报表不显示仓库库位。', 'Storage bins are not shown in this report.': '本报表不显示库位明细。',
  'Some figures may be incomplete for this range.': '部分数据可能不完整。',
  'No business records in this range. Adjust the filters or add business data.': '当前范围暂无业务记录，可调整筛选或录入业务数据。',
  'Date range': '日期范围', 'This month': '本月', 'Last 3 months': '近 3 个月', 'Year to date': '今年至今', 'Last 12 months': '近 12 个月', 'All dates': '全部日期',
};
const english = Object.fromEntries(Object.entries(chinese).map(([en, zh]) => [zh, en]));
export function analyticsCopy(value: string, language: string) {
  return language === 'en-US' ? english[value] || value : chinese[value] || value;
}

export function reportStatusCopy(value: string, language: string) {
  const states: Record<string, [string, string]> = {
    fully_received: ['Fully received', '全部收货'], pending_approval: ['Pending approval', '待审批'], rejected: ['Rejected', '已拒绝'],
    shortage_risk: ['Shortage risk', '缺货风险'], partially_fulfilled: ['Partially fulfilled', '部分履约'], fulfilled: ['Fulfilled', '已履约'],
    ready_to_ship: ['Ready to ship', '可发货'], partially_allocated: ['Partially allocated', '部分分配'], on_hold: ['On hold', '已暂停'],
    issued: ['Issued', '已下达'], partially_received: ['Partially received', '部分收货'], received: ['Received', '已收货'],
    open: ['Open', '进行中'], closed: ['Closed', '已关闭'], cancelled: ['Cancelled', '已取消'], completed: ['Completed', '已完成'],
    draft: ['Draft', '草稿'], approved: ['Approved', '已批准'], active: ['Active', '启用'], inactive: ['Inactive', '停用'],
    high: ['High', '高'], medium: ['Medium', '中'], low: ['Low', '低'], unknown: ['Unknown', '未知'],
    partial: ['Partial', '部分履约'], delivered: ['Delivered', '已交付'], confirmed: ['Confirmed', '已确认'],
    out_of_stock: ['Out of stock', '缺货'], below_safety_stock: ['Below safety stock', '低于安全库存'],
    below_reorder_point: ['Below reorder point', '低于再订货点'], ok: ['In stock', '库存正常'],
    submitted: ['Submitted', '已提交'], matching: ['Matching', '匹配中'], exception: ['Exception', '有差异'], matched: ['Matched', '已匹配'],
    held: ['Held', '已暂挂'], pending: ['Pending', '待处理'], variance: ['Variance', '有差异'], canceled: ['Cancelled', '已取消'],
  };
  const pair = states[value];
  return pair ? pair[language === 'en-US' ? 0 : 1] : analyticsCopy(value, language);
}
