import { useCallback } from "react";
import { useI18n } from "../../i18n/I18n";
import { statusCodeLabel } from "../../i18n/statusLabels";

// Display copy for Today (/app/overview/risks). English is the source; zh-CN
// is chosen by the interface language. The server sends codes, ids, dates and
// numbers (GET /api/home/overview); names, SKUs, units and document numbers
// stay as stored. A message with a count has a "One" form for a count of 1.
const COPY = {
  "en-US": {
    loadFailed: "Could not load overview",
    retry: "Retry",
    loading: "Loading",
    refresh: "Refresh overview",
    workTitle: "Today's work",
    workNote: "Earliest date first. Each row opens its record.",
    noWork: "Nothing needs action right now",
    noWorkHint: "Overdue or due purchase orders, items to reorder, supplier invoices, customer invoices, overdue receivables and sales orders to reserve or ship appear here.",
    noOverdueWork: "Nothing is overdue",
    showAll: "Show all {n}",
    showFewer: "Show fewer",
    moreNotShown: "{n} more are not shown here",
    hiddenNote: "Not listed for your role: {kinds}.",
    hiddenPurchasing: "purchasing",
    hiddenInventory: "stock to reorder",
    hiddenBills: "supplier invoices",
    hiddenSalesOrders: "sales orders",
    hiddenCustomerInvoices: "customer invoices",
    hiddenReceivables: "receivables",
    hiddenContracts: "contracts",
    reorderScope: "Stock to reorder is worked out across every warehouse, and your role sees only some of them, so items to reorder are not listed here.",
    notChecked: "Could not be checked just now: {sources}.",
    sourceReorder: "stock to reorder",
    sourceCustomerInvoices: "customer invoices",
    sourceReceivables: "receivables",
    sourcePurchaseOrders: "purchase orders",
    sourceContracts: "contracts",
    sourceSetup: "setup steps",
    sourceDatabase: "stock to reorder, customer invoices and receivables",
    truncated: "Not every record could be read ({subjects}), so the list may be incomplete.",
    kind_purchase_order_overdue: "Purchase order overdue",
    kind_purchase_order_due: "Purchase order due",
    kind_reorder_now: "Reorder now",
    kind_bill_exception: "Supplier invoice match exception",
    kind_bill_to_approve: "Supplier invoice ready to approve",
    kind_bill_to_match: "Supplier invoice ready to match",
    kind_bill_awaiting_receipt: "Supplier invoice waiting for its receipt",
    kind_customer_invoice_to_issue: "Customer invoice approved, not issued",
    kind_receivable_overdue: "Receivable overdue",
    kind_sales_order_to_reserve: "Sales order to reserve",
    kind_sales_order_to_ship: "Sales order to ship",
    kind_purchase_order_to_approve: "Purchase order awaiting approval",
    kind_purchase_request_to_approve: "Purchase request awaiting approval",
    kind_purchase_request_to_convert: "Purchase request ready for conversion",
    kind_draft_purchase_order: "Draft PO awaiting review",
    kind_contract_notice_due: "Contract notice due",
    kind_contract_ending: "Contract ending",
    kind_contract_past_end: "Contract past its end date",
    overdueDays: "{n} days overdue",
    overdueDaysOne: "1 day overdue",
    lateDays: "{n} days late",
    lateDaysOne: "1 day late",
    dueToday: "Due today",
    dueOn: "Due {date}",
    orderToday: "Order today",
    orderBy: "Order by {date}",
    invoiceOn: "Invoice date {date}",
    promisedToday: "Promised today",
    promisedOn: "Promised {date}",
    neededBy: "Needed by {date}",
    noticeBy: "Give notice by {date}",
    noticeToday: "Last day to give notice",
    endsOn: "Ends {date}",
    endsToday: "Ends today",
    endedDays: "Ended {n} days ago",
    endedDaysOne: "Ended 1 day ago",
    noDate: "No date",
    stillToReceive: "{qty} still to receive",
    receivedOf: "{received} of {ordered} received",
    linesToReceive: "{n} lines still to receive",
    linesToReceiveOne: "1 line still to receive",
    notIssued: "Not issued to the supplier yet",
    supplier: "Supplier {name}",
    customer: "Customer {name}",
    position: "Stock position {position}, reorder point {reorderPoint}",
    belowSafety: "Below safety stock",
    shortage: "Open sales orders exceed available stock",
    openReorderList: "Open reorder list",
    billAwaitingReceipt: "Link the receipt, then match",
    billToMatch: "Ready for the three-way match",
    billToApprove: "Matched; waiting for approval",
    billException: "Review the match exception",
    amount: "Amount {amount}",
    issueToCustomer: "Approved; issue it to the customer",
    owed: "{amount} still owed",
    owedHidden: "Money still owed",
    disputed: "Disputed",
    toReserve: "{qty} still to reserve",
    linesToReserve: "{n} lines still to reserve",
    linesToReserveOne: "1 line still to reserve",
    toShip: "{qty} still to ship",
    linesToShip: "{n} lines still to ship",
    linesToShipOne: "1 line still to ship",
    requestAmount: "Request amount {amount}",
    requestConvert: "Approved; ready to create the purchase order",
    awaitingApproval: "Waiting for approval",
    renewsUnlessNotice: "Renews automatically on {date} unless notice is given",
    recordNewEnd: "Renewed automatically: record the new end date",
    recordOutcome: "Record a renewal, or terminate it",
    renewByAgreement: "Renews by agreement",
    tileWork: "Needs action",
    tileWorkNote: "Every row in Today's work",
    tileOverdue: "Overdue",
    tileOverdueNote: "Past their date. Select to list only these",
    tileChanges: "Documents updated today",
    changesNote: "Documents you can open whose last change was today ({date}). A document changed several times counts once.",
    changesShort: "Last changed on {date}",
    setupTitle: "Set up your workspace",
    setupNote: "{done} of {total} steps done. This list goes away once every step is done.",
    step_items: "Import items",
    step_suppliers: "Import suppliers",
    step_customers: "Import customers",
    step_opening_stock: "Import opening stock",
    step_teammates: "Invite a teammate",
    stepDone: "Done ({n})",
    stepOpen: "Not started",
    stepStart: "Start",
    stepAskAdmin: "Ask an administrator",
    stepUnavailable: "Not turned on in this workspace",
    recentTitle: "Recent documents",
    recentNote: "The latest purchasing, receiving, sales and invoice documents you can open, most recently changed first.",
    recentEmpty: "No recent documents",
    recentEmptyHint: "Documents appear here once a purchase request, purchase order, sales order or invoice is created.",
    colType: "Type",
    colNumber: "Document number",
    colStatus: "Status",
    colPartner: "Supplier or customer",
    colAmount: "Amount",
    colUpdated: "Updated",
    type_purchase_request: "Purchase request",
    type_rfq: "RFQ",
    type_purchase_order: "Purchase order",
    type_receipt: "Receipt",
    type_supplier_invoice: "Supplier invoice",
    type_sales_order: "Sales order",
    type_customer_invoice: "Customer invoice",
  },
  "zh-CN": {
    loadFailed: "首页数据加载失败",
    retry: "重试",
    loading: "加载中",
    refresh: "刷新首页",
    workTitle: "今日需处理",
    workNote: "按日期从早到晚排列，每行可打开对应记录。",
    noWork: "暂无待处理事项",
    noWorkHint: "逾期或即将到期的采购订单、需补货物料、采购发票、销售发票、逾期应收款，以及待预留或待发货的销售订单会显示在这里。",
    noOverdueWork: "暂无逾期事项",
    showAll: "显示全部 {n} 项",
    showFewer: "收起",
    moreNotShown: "另有 {n} 项未在此显示",
    hiddenNote: "你的角色无法查看，未列出：{kinds}。",
    hiddenPurchasing: "采购",
    hiddenInventory: "需补货物料",
    hiddenBills: "采购发票",
    hiddenSalesOrders: "销售订单",
    hiddenCustomerInvoices: "销售发票",
    hiddenReceivables: "应收款",
    hiddenContracts: "合同",
    reorderScope: "补货按全部仓库计算，你的角色只能查看部分仓库，因此这里不列出需补货物料。",
    notChecked: "暂时无法检查：{sources}。",
    sourceReorder: "需补货物料",
    sourceCustomerInvoices: "销售发票",
    sourceReceivables: "应收款",
    sourcePurchaseOrders: "采购订单",
    sourceContracts: "合同",
    sourceSetup: "设置步骤",
    sourceDatabase: "需补货物料、销售发票和应收款",
    truncated: "部分记录未能全部读取（{subjects}），列表可能不完整。",
    kind_purchase_order_overdue: "采购订单逾期",
    kind_purchase_order_due: "采购订单即将到期",
    kind_reorder_now: "需立即补货",
    kind_bill_exception: "采购发票匹配异常",
    kind_bill_to_approve: "采购发票待审批",
    kind_bill_to_match: "采购发票待匹配",
    kind_bill_awaiting_receipt: "采购发票待关联收货",
    kind_customer_invoice_to_issue: "销售发票已批准未开出",
    kind_receivable_overdue: "应收款逾期",
    kind_sales_order_to_reserve: "销售订单待预留",
    kind_sales_order_to_ship: "销售订单待发货",
    kind_purchase_order_to_approve: "采购订单待审批",
    kind_purchase_request_to_approve: "采购申请待审批",
    kind_purchase_request_to_convert: "采购申请待转换",
    kind_draft_purchase_order: "Draft PO 待复核",
    kind_contract_notice_due: "合同通知截止将至",
    kind_contract_ending: "合同即将到期",
    kind_contract_past_end: "合同已过到期日",
    overdueDays: "逾期 {n} 天",
    overdueDaysOne: "逾期 1 天",
    lateDays: "已晚 {n} 天",
    lateDaysOne: "已晚 1 天",
    dueToday: "今天到期",
    dueOn: "{date} 到期",
    orderToday: "今天下单",
    orderBy: "{date} 前下单",
    invoiceOn: "发票日期 {date}",
    promisedToday: "承诺今天交付",
    promisedOn: "承诺日期 {date}",
    neededBy: "需求日期 {date}",
    noticeBy: "请在 {date} 前发出通知",
    noticeToday: "今天是通知截止日",
    endsOn: "{date} 到期",
    endsToday: "今天到期",
    endedDays: "已到期 {n} 天",
    endedDaysOne: "已到期 1 天",
    noDate: "无日期",
    stillToReceive: "仍待收货 {qty}",
    receivedOf: "已收货 {received} / {ordered}",
    linesToReceive: "{n} 行仍待收货",
    linesToReceiveOne: "1 行仍待收货",
    notIssued: "尚未下达给供应商",
    supplier: "供应商 {name}",
    customer: "客户 {name}",
    position: "库存头寸 {position}，再订货点 {reorderPoint}",
    belowSafety: "低于安全库存",
    shortage: "未结销售订单超过可用库存",
    openReorderList: "打开补货清单",
    billAwaitingReceipt: "先关联收货单，再匹配",
    billToMatch: "可进行三单匹配",
    billToApprove: "已匹配，等待审批",
    billException: "复核匹配异常",
    amount: "金额 {amount}",
    issueToCustomer: "已批准，待开给客户",
    owed: "仍欠 {amount}",
    owedHidden: "仍有欠款",
    disputed: "有争议",
    toReserve: "仍待预留 {qty}",
    linesToReserve: "{n} 行仍待预留",
    linesToReserveOne: "1 行仍待预留",
    toShip: "仍待发货 {qty}",
    linesToShip: "{n} 行仍待发货",
    linesToShipOne: "1 行仍待发货",
    requestAmount: "申请金额 {amount}",
    requestConvert: "审批已完成，等待创建采购订单",
    awaitingApproval: "等待审批",
    renewsUnlessNotice: "如不发出通知，将于 {date} 自动续约",
    recordNewEnd: "已自动续约：请记录新的到期日",
    recordOutcome: "请记录续约，或终止合同",
    renewByAgreement: "协商续约",
    tileWork: "待处理",
    tileWorkNote: "今日需处理中的全部事项",
    tileOverdue: "已逾期",
    tileOverdueNote: "已过日期；点选后只列出这些",
    tileChanges: "今日更新的单据",
    changesNote: "今天（{date}）最后一次更改、你有权打开的单据；同一单据多次更改只计一次。",
    changesShort: "最后更改于 {date}",
    setupTitle: "设置工作区",
    setupNote: "已完成 {done}/{total} 步。全部完成后此清单会自动隐藏。",
    step_items: "导入物料",
    step_suppliers: "导入供应商",
    step_customers: "导入客户",
    step_opening_stock: "导入期初库存",
    step_teammates: "邀请同事",
    stepDone: "已完成（{n}）",
    stepOpen: "未开始",
    stepStart: "开始",
    stepAskAdmin: "请联系管理员",
    stepUnavailable: "此工作区未启用",
    recentTitle: "最近单据",
    recentNote: "你有权打开的采购、收货、销售和发票单据，最近更改的在前。",
    recentEmpty: "暂无近期单据",
    recentEmptyHint: "创建采购申请、采购订单、销售订单或发票后，单据会显示在这里。",
    colType: "类型",
    colNumber: "单号",
    colStatus: "状态",
    colPartner: "供应商或客户",
    colAmount: "金额",
    colUpdated: "更新时间",
    type_purchase_request: "采购申请",
    type_rfq: "询价",
    type_purchase_order: "采购订单",
    type_receipt: "收货单",
    type_supplier_invoice: "采购发票",
    type_sales_order: "销售订单",
    type_customer_invoice: "销售发票",
  },
} as const;

export type TodayCopyKey = keyof (typeof COPY)["en-US"];

export function todayText(language: string, key: TodayCopyKey, params: Record<string, string | number> = {}) {
  const table = COPY[language === "zh-CN" ? "zh-CN" : "en-US"];
  return Object.entries(params).reduce((value, [name, replacement]) => value.split(`{${name}}`).join(String(replacement)), table[key] as string);
}

// The "One" form of a message for a count of 1, else the message.
export function todayCount(language: string, key: TodayCopyKey, count: number, params: Record<string, string | number> = {}) {
  const one = `${key}One` as TodayCopyKey;
  return todayText(language, count === 1 && one in COPY["en-US"] ? one : key, { n: count, ...params });
}

// Statuses the shared labels do not cover, for the document types Today lists.
const EXTRA_STATUS: Record<string, [string, string]> = {
  confirmed: ["Confirmed", "已确认"],
  fulfilled: ["Fulfilled", "已完成"],
  matching: ["Matching", "匹配中"],
  held: ["On hold", "已暂停"],
  paid: ["Paid", "已付款"],
  void: ["Void", "已作废"],
  voided: ["Void", "已作废"],
  export_ready: ["Ready to export", "待导出"],
};

// A stored status code as a label. A code no table knows reads as words in
// English ("ready_to_ship" is "Ready to ship") and stays as stored in Chinese.
export function todayStatusLabel(code: string, language: string) {
  const value = String(code || "").trim();
  if (!value) return "—";
  const shared = statusCodeLabel(value, language);
  if (shared) return shared;
  const extra = EXTRA_STATUS[value];
  if (extra) return extra[language === "en-US" ? 0 : 1];
  if (language !== "en-US" || !/^[a-z]+(_[a-z]+)*$/.test(value)) return value;
  const words = value.replace(/_/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function useTodayCopy() {
  const { language } = useI18n();
  const t = useCallback((key: TodayCopyKey, params?: Record<string, string | number>) => todayText(language, key, params), [language]);
  const count = useCallback((key: TodayCopyKey, n: number, params?: Record<string, string | number>) => todayCount(language, key, n, params), [language]);
  const status = useCallback((code: string) => todayStatusLabel(code, language), [language]);
  return Object.assign(t, { count, status, language });
}
