// English display copy for the sales order and shipment workbench. Display
// labels only: never apply this mapping to stored business values.
export const outboundEnglish: Record<string, string> = {
  "可用量 = 在库量 - 预留量": "Available = on hand − reserved",
  "预留量 + 已履约量不超过订购量": "Reserved + fulfilled does not exceed ordered",
  "网络连接失败，请检查连接后重试。": "Could not connect. Check your connection and try again.",
  "登录已失效，请重新登录后读取销售订单。": "Your session has expired. Sign in again to load sales orders.",
  "当前账号没有读取销售订单的权限。": "Your account cannot view sales orders.",
  "销售订单服务暂时不可用，请稍后重试。": "Sales orders are temporarily unavailable. Try again later.",
  "当前角色只能查看，不能执行此操作。": "Your role can view but not perform this action.",
  "当前账号没有相关仓库权限。": "Your account has no access to this warehouse.",
  "销售订单当前已暂停，不能执行发货过账。请先恢复订单。": "This sales order is on hold, so shipments cannot be posted. Resume the order first.",
  "当前销售订单写入能力未启用，页面保持只读。": "Sales order changes are not enabled, so this page is read only.",
  "订单已发生变化，请刷新后重新预览。": "The order has changed. Refresh and preview again.",
  "发货单已变化，请刷新后重新预览。": "The shipment has changed. Refresh and preview again.",
  "库存已发生变化，请刷新后重新预览。": "Inventory has changed. Refresh and preview again.",
  "操作内容已改变，请重新开始该操作。": "The request changed. Start the action again.",
  "该操作正在处理中，请稍后重试。": "This action is still being processed. Try again shortly.",
  "可用库存不足，请调整数量。": "Not enough available stock. Adjust the quantity.",
  "历史出库事实不一致，系统已阻止冲销。": "Past outbound records do not match, so the reversal was blocked.",
  "发货单号已存在，请更换号码。": "This shipment number is already in use. Choose another.",
  "销售订单号已存在，请更换号码。": "This sales order number is already in use. Choose another.",
  "当前订单状态不允许此操作。": "The order's current status does not allow this action.",
  "订单物料与当前工作区主数据不一致。": "The order's items do not match this workspace's item master.",
  "返回销售订单列表": "Back to sales orders",
  "新建销售订单草稿": "New sales order draft",
  "SKU、物料名称与单位由 PostgreSQL Item 主数据快照。": "SKU, item name, and unit are copied from the item master.",
  "保存中…": "Saving…",
  "业务调整": "Business adjustment",
  "正在读取正式订单…": "Loading the order…",
  "当前页面仅显示您有权查看的仓库数据，部分库存或履约事实已隐藏。": "Only warehouses you can access are shown. Some inventory or fulfillment records are hidden.",
  "当前订单包含多条订单行。为避免不完整覆盖，窄版界面暂不支持编辑该草稿。": "This order has several lines. To avoid overwriting some of them, this draft cannot be edited on a narrow screen.",
  "编辑草稿": "Edit draft",
  "确认订单": "Confirm order",
  "恢复": "Resume",
  "订单行与库存可用性": "Order lines and availability",
  "库存预留": "Reserved stock",
  "预留 ID": "Reservation ID",
  "已分配": "Allocated",
  "已消耗": "Consumed",
  "已释放": "Released",
  "可释放": "Releasable",
  "暂无发货单。": "No shipments yet.",
  "流水 ID": "Movement ID",
  "入": "In",
  "出": "Out",
  "完整订单对账无法在当前权限范围内确认。": "The full order reconciliation cannot be confirmed with your access.",
  "编辑客户": "Edit customer",
  "编辑数量": "Edit quantity",
  "订单行": "Order line",
  "请选择订单行": "Select an order line",
  "请选择库存余额": "Select an inventory balance",
  "请选择预留记录": "Select a reservation",
  "交易数量": "Quantity",
  "释放原因": "Release reason",
  "必须先读取服务端预览，前端不计算权威库存。": "Load the server preview first. The page does not calculate inventory itself.",
  "读取预览": "Load preview",
  "正在读取发货单…": "Loading the shipment…",
  "PostgreSQL 正式记录": "Posted record",
  "无冲销原因": "No reversal reason",
  "取消草稿": "Cancel draft",
  "过账发货": "Post shipment",
  "冲销发货": "Reverse shipment",
  "冲销流水": "Reversal movement",
  "发货时在库量与预留量同时下降，因此可用量不会再次下降。冲销没有“强制绕过”选项。": "Shipping lowers on-hand and reserved stock together, so available stock does not drop again. A reversal cannot be forced.",
  "暂无记录。": "No records.",
  "暂无证据事件。": "No evidence events.",
  // Labels the order workbench API returns for its related-record links and explanation.
  "预留记录": "Reservations",
  "暂无预留记录": "No reservations",
  "发货单": "Shipments",
  "暂无发货单": "No shipments",
  "库存余额": "Inventory balances",
  "存在多个库存目标，请在库存页面手动筛选": "Several inventory balances match. Filter on the inventory page.",
  "当前授权仓库没有余额记录": "No balances in the warehouses you can access",
  "库存流水": "Inventory movements",
  "暂无库存流水": "No inventory movements",
  "审计记录": "Audit log",
  "当前仅能解释已授权仓库范围，完整履约事实已隐藏。": "Only warehouses you can access are explained. Some fulfillment records are hidden.",
  "当前订单的库存、预留与履约事实一致。": "Inventory, reservations, and fulfillment for this order are consistent.",
  "当前订单存在需要人工复核的对账差异。": "This order has reconciliation differences to review.",
  "默认库位": "Default location",
  "现有 {n}": "On hand {n}",
  "预留 {n}": "Reserved {n}",
  "可用 {n}": "Available {n}",
  "可操作": "Available",
  "只读": "Read only",
  "计算 {calculated} / 记录 {recorded}": "calculated {calculated} / recorded {recorded}",
  "命令记录": "Command",
  "幂等键": "Idempotency key",
  "暂停订单": "Put on hold",
  "预留量": "Reserved",
};
